### ISSUE TITLE
Dynamic Activity List

### ISSUE THREAD

**Issue by thehale** [thehale/SimpleTimeTracker-WearOS#3]
Currently, the app hard-codes the list -- specifically what I used several months ago --, meaning any customization requires a complete re-build/install of the app.

~**Good:** Allow the companion app to add/remove activities visible to the watch~
~- Pros: No need to modify Razeeman's app.~
~- Cons: Users would need to manually mirror activities/tags between the WearOS version and the official app.~

~**Better:** Add an Intent API to Razeeman's app for querying all available activities (+ colors)~
~- Pros: Keeps the watch's set of activities and tags *automatically* in sync with the official app~
~- Cons: Requires modifying Razeeman's app.~

✅ **Best:** Integrate the WearOS app directly into Razeeman's app, and build a MessageClient there instead of an Intent API
 - Pros: The best long-term experience for developers and users.
 - Cons: Requires modifying Razeeman's app. Possibly the hardest option on the list.

Remaining steps after https://github.com/thehale/SimpleTimeTracker-WearOS/commit/9614a5cb04f29a8d52e1a55dc4ef9ec8220bdc6e for a full MVP:
 - [ ] Add support on Wear for all icons supported by mobile

Work on the actual functionality for tapping an activity chip and having it start the activity on the phone will be tracked in #5

**Comment by thehale** [comment]
Proposed data schema on the watch, regardless of the communication pattern.

```jsonc
{
  "CATEGORY_NAME": {
    "color": "HEX_CODE",
    "tags": [
      {"name": "TAG_NAME", "color": "HEX_CODE" },
      //...
    ]
  },
  //...
}
```

**Comment by kantahrek** [comment]
The pattern that Razeeman's been using over in SimpleTimeTracker is a [Notification Broadcast Receiver](https://github.com/Razeeman/Android-SimpleTimeTracker/blob/dev/features/feature_notification/src/main/java/com/example/util/simpletimetracker/feature_notification/recevier/NotificationReceiver.kt) that is responsible for routing all received intents to their corresponding controllers. For the sake of prototyping I've piggy-backed on this model, but it doesn't lend itself well to the synchronous call & response as you mentioned that one might prefer, akin to making a server call. Since the "START_ACTIVITY" and "STOP_ACTIVITY" intents are currently handled in that receiver, I think we'll need to get buy-in from Razeeman and partially change it over to an Activity model to get synchronous responses with record data.

**Comment by thehale** [comment]
I've completed the **Best** option and successfully integrated the WearOS app directly into Razeeman's application which greatly simplifies the communication protocol (see #8).

Now, you should be able to just call `WearRPCClient.queryActivities` to get the data required to render out a list of activity chips to reflecting the currently available activities within the phone app.

**Comment by thehale** [comment]
Next steps after https://github.com/thehale/SimpleTimeTracker-WearOS/commit/9614a5cb04f29a8d52e1a55dc4ef9ec8220bdc6e for a full MVP:
 - [ ] Tapping an activity starts that activity (replacing any other running activity)
     - Note, #5 will require navigating to a tag selector before firing off the activity. Not required for this ticket, but upcoming in the near future.
 - [ ] Add support on Wear for all icons supported by mobile (optional, but highly desired)

**Comment by thehale** [comment]
The final outstanding step for this ticket is to render all activity icons on the Watch. 

Currently, text and emoji icons render, but actual SVGs do not.

 We'll have to review how Razeeman turns a string icon name (they all start with `ic_`) into an actual SVG render, then replicate that on the watch.

**Comment by thehale** [comment]
I'm considering this ticket closed since the Activities render dynamically. The shortcoming surrounding the SVG icons will be tracked separately in #11.
